### ISSUE TITLE
Questions on hifitime (not an issue)

### ISSUE THREAD

**Issue by ChristopherRabotin** [MWATelescope/Marlu#19]
Hi folks,

First off, a million thanks for using hifitime. It's always a pleasure to see my code in use.

Secondly, I'm trying to figure out what other features would be useful for the few who use the library. The first ones that come to mind are the support for other time systems like TCB and TCG: is that of interest to your work? Do you have any suggestions for improvement?

Thanks,
Chris

**Comment by d3v-null** [comment]
A million thanks for making hifitime!

You've done an amazing job, and It's genuinely a really solid library. It supports all the time systems we use, and has great ergonomics. 

I think keeping dependencies simple, and libraries minimalist is a good thing, I can't think of anything hifitime desparately needs, but I'll keep in mind that you're keen for suggestions, and open an issue if I do. 

Thanks!

**Comment by cjordan** [comment]
Hi Chris,

Thanks for reaching out.  I personally think `hifitime` is already in a generally good state.  I have a (bad) habit of tinkering with things that subtly irritate me, but `hifitime` has been spared of my attention, I suppose because I see no issue with it.  I will, of course, let you know if I find something to improve.

Long shot - recently, we've started incorporating DUT1 into our work, and it does feel a bit clunky to add this float to existing `hifitime::Epoch`s.  Perhaps it would be worth having `Epoch`s track which time system they're using?

Cheers,
Chris
